### ISSUE TITLE
Writing good unit tests

### ISSUE THREAD

**Issue by sean-ww** [mkjs/talks#22]
It would great to see some examples of real world unit tests, and to understand where they have been useful.
(I'm an absolute beginner at writing unit tests, so it would be great if someone all powerful could share their wisdom and present this)

**Comment by jamescoward** [comment]
Hi @sean-ww thanks for the suggestion! We'll see what we can organise 👍

**Comment by jamescoward** [comment]
Hi @sean-ww we've decided to try out a new thing next event where we will have a group discussion instead of a second talk. I think we will get some good input from the community :)

**Comment by sean-ww** [comment]
OK, that should be good thanks.

**Comment by jamescoward** [comment]
I'll still keep a look out for someone who could give a talk on the topic as well.

**Comment by davidjgoss** [comment]
So, I thought we could post links here related to some of the bits and pieces we talked about, and people can weigh in with stuff and/or ask questions in the comments.

To start with, someone mentioned the practise of having tons of unit tests because they're cheap and fast, and fewer e2e tests because they have a higher cost. I've heard this talked about as part of the "testing pyramid" (predictably [Martin Fowler has a good article](https://martinfowler.com/bliki/TestPyramid.html) on it) and also found [this post interesting about the "cupcake" shape](https://www.thoughtworks.com/insights/blog/introducing-software-testing-cupcake-anti-pattern) that is unfortunately more familiar to lots of teams.

**Comment by davidjgoss** [comment]
Also some links to JS testing libs/frameworks we mentioned:

- https://mochajs.org/
- https://jasmine.github.io/
- https://facebook.github.io/jest/

Also I spotted this one a while ago which looks really awesome https://github.com/avajs/ava

**Comment by jamescoward** [comment]
To add to that
 - http://sinonjs.org/
 - http://airbnb.io/enzyme/index.html
 - http://chaijs.com/
 - https://github.com/producthunt/chai-enzyme
 - https://github.com/node-nock/nock
